# Generated by Django 6.0 on 2026-08-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_server', '0008_flight_process_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumedNonce',
            fields=[
                ('nonce', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('process_id', models.IntegerField()),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
